name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
#    - name: configure
#      run: ./configure
    - name: make
      run: make
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
    - name: upload binaries
      uses: actions/upload-artifact@v3
      with: 
          name: Ubuntu binaries
          path: bin
  macos-build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
#    - name: configure
#      run: ./configure
    - name: make
      run: make
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
    - name: upload binaries
      uses: actions/upload-artifact@v3
      with: 
          name: MacOS binaries
          path: bin
  windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
            choco uninstall mingw
            choco install mingw --version=4.9.3 --force
    - name: make
      run: .\make.bat
    - name: upload binaries
      uses: actions/upload-artifact@v2
      with: 
          name: Windows executables
          path: exe
