name: C/C++ CI development branch sancheck

on:
  push:
    branches: [ "development" ]

jobs: 
  precheck-and-update-tutorial:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          token: ${{ secrets.MY_GITHUB_ACTION_TOKEN }}
    - name: make
      run: make tutorial
    - name: commit
      run: |
            git config --local user.email "github-actions[bot]@github.com"
            git config --local user.name "github-actions[bot]"
            git add tutorial/*
            git commit -m "update tutorials"
    - name: push
      uses: chaoszhang/github-push-action@master
      with: 
          github_token: ${{ secrets.MY_GITHUB_ACTION_TOKEN }}
          branch: temp
          force: true
